openapi: 3.0.0

tags:
  - name: Setting Variables
    description: Setting an Env-Variable.

servers:
  - url: https://envhub.ryanbaig.vercel.app/api/
    description: Production server
paths:
  /vars/set:
    post:
      tags:
        - Setting Variables
      summary: Set a Variable.
      description: Set a Variable.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                varName:
                  type: string
                varValue:
                  type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: "Variable added to the database successfully."
                  varName:
                    type: string
                    example: "YourVariableName"
                  varValue:
                    type: string
                    example: "YourVariableValue"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 400
                  error:
                    type: string
                    example: "'varName' and 'varValue' parameters are required. Make sure they are present and try again."
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 409
                  error:
                    type: string
                    example: "varName already exists. Please use a different name and Try again."
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 500
                  error:
                    type: string
                    example: "Internal Server Error Message"
                  logging:
                    type: object
                    properties:
                      result:
                        type: string
                        example: "Error Result"
                      VarName:
                        type: string
                        example: "Error Variable Name"

security:
  - EnvHub Account API Key: [] # Use the name of your security scheme here

components:
  securitySchemes:
    EnvHub Account API Key:
      type: apiKey
      in: header # You can specify "query" if your API key is passed as a query parameter
      name: Authorization # Name of the header or query parameter
